### ISSUE TITLE
"High" background

### ISSUE THREAD

**Issue by vitalii2011** [yumi-modding/FS19_CombineXP#20]
After the last update 1.0.1.0

**Comment by yumi-modding** [comment]
Hello
Thx I missed this issue but I realized it could be there after push to modhub.
This is ok when playing with seasons since crop moisture is displayed there.
I will fix on next update.

**Comment by vitalii2011** [comment]
A little late before closing. ) 
Now all harvesters from the first to the top ones work in the fields at a speed of 3 km/h, a little slow, at least 5 would be normal.

**Comment by yumi-modding** [comment]
Do you have seasons activated ? If no, what time is it when you harvest?

**Comment by vitalii2011** [comment]
There are no Seasons in the /mods folder. 
In the afternoon, in sunny weather.

**Comment by yumi-modding** [comment]
Ok, if you could please share all details like vehicles, crop, yield... so I can see if I understand because in this situation you should reach max speed.

**Comment by vitalii2011** [comment]
If it's necessary, I can try to find a save where these combines worked in other, different fields at a speed of 3 km/h.

**Comment by yumi-modding** [comment]
Hello @vitalii2011 ,

If it's 8:48am when harvesting, I consider it's too early to harvest as stated in this chart. In my experience you won't start harvesting cereal in the morning before 10am or 11am in good conditions.
So here you're supposed to reach ~30% of max speed. From 10am you'll reach 40% and 90% at noon.
I would like to make this computation as a setting (on/off) because I expect a lot of people will not understand why they are harvesting at low speed, but I need to make the UI for this.

![image](https://user-images.githubusercontent.com/23509583/104761694-92ba6500-5763-11eb-88dc-eff9af5ce041.png)

**Comment by vitalii2011** [comment]
All clear.

**Comment by vitalii2011** [comment]
Hi @yumi-modding 
-Thanks for updating 1.0.1.1. 
-Maybe it makes sense to add the above graph to the illustrations on ModHub? Because the forums still do not understand why: "... many combines simply do not go when harvesting.(... многие комбайны просто не едут при уборке.)" 
And knowing how rarely we read the descriptions :) , it would probably be a good solution to add an appearing inscription under the HUD: ~"daily speed reduction" - in the interval 03:00 - 11:00.

**Comment by yumi-modding** [comment]
Hello @vitalii2011 
You're right. I had put a screenshot of xml file but it's not visible in modhub.
I should use moisture icon location to explain speed reduction yes.
Thx for the feedback

**Comment by vitalii2011** [comment]
> I had put a screenshot of xml file but it's not visible in modhub.

Maybe your screenshot does not meet the site's requirements for resolution or format?  Judging from my experience with Steam.
