### ISSUE TITLE
Add Russian translation

### ISSUE THREAD

**Issue by yumi-modding** [yumi-modding/FS19_CombineXP#9]
https://pastebin.com/MU0wHqQ4

Thanks nagor

**Comment by vitalii2011** [comment]
- By the same link for 1.0.0.2
- Changed for myself in xpCombine.lua in lines 598 and 600 to "т/ч" and "т/га" respectively, but maybe it's possible to translate this in <l10n> in modDesc.xml? https://i.imgur.com/n7tyhIe.png 
- The field "<ru> <! [CDATA [...]]> </ru>" was translated simply "because it is not difficult" - ModHub still only supports en, de, fr and pl and the description in the game, for Russian localization, for example, will be in English, but "<title>… </title>" and "<l10n>… </l10n>" are displayed in the game in the selected language.
